print('ytfjghkhb')
print('t657i8uiuytr346syrdcvhbjn')
print('cvhbjnkml,')
print('txcfgvhbjnlkml')
print('sdtfvbncxdfgh')
print('dtyujjhvccv')
print('dfjkjlkm,')
print('rsdfghiuxeas456u7')
print('hucg gytyuu98uc')
print('uytdtryfguh8i')
